package sgme.carder;


import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Senghor AKOMINON
 */
public class JChangerPassword extends javax.swing.JDialog {

    /**
     * Creates new form JChangerPassword
     */
    private Statement chargeur;
    private final JDBConnection bd;
    int numUtilisateur = 0;String Host = null, user = null, Password =null;
    
    /**
     *
     * @param parent
     * @param modal
     * @param numUtilisateur
     * @param Host
     * @param User
     * @param Password
     */
    public JChangerPassword(java.awt.Frame parent, boolean modal, int numUtilisateur, String Host, String User, String Password) {
        super(parent, modal);
        initComponents();
        this.actuelMotPasse.setEchoChar('*');this.confirmerNouveauMotDePasse.setEchoChar('*');this.modifyPassword.setVisible(false);
        bd = new JDBConnection();
        this.numUtilisateur = numUtilisateur;this.Host = Host;this.user = User; this.Password = Password;        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NouveauMotDePasse = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        modifyPassword = new javax.swing.JButton();
        actuelMotPasse = new java.awt.TextField();
        confirmerNouveauMotDePasse = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Changer mot de passe");
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(51, 51, 255)))); // NOI18N
        jPanel1.setToolTipText("Changer votre mot de passe");

        NouveauMotDePasse.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NouveauMotDePasse.setForeground(new java.awt.Color(0, 0, 255));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Confirmer mot de passe");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Nouveau mot de passe");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Actuel mot de passe");

        modifyPassword.setBackground(new java.awt.Color(255, 255, 255));
        modifyPassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        modifyPassword.setText("Modifier mot de passe");
        modifyPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 153, 153))));
        modifyPassword.setMargin(new java.awt.Insets(2, 1, 2, 1));
        modifyPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyPasswordMouseClicked(evt);
            }
        });

        actuelMotPasse.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        actuelMotPasse.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                actuelMotPasseTextValueChanged(evt);
            }
        });

        confirmerNouveauMotDePasse.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        confirmerNouveauMotDePasse.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                confirmerNouveauMotDePasseTextValueChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NouveauMotDePasse)
                    .addComponent(actuelMotPasse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmerNouveauMotDePasse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(modifyPassword)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(actuelMotPasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(NouveauMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(confirmerNouveauMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(modifyPassword)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifyPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyPasswordMouseClicked
        String text1 = NouveauMotDePasse.getText(), text2= confirmerNouveauMotDePasse.getText(),text = actuelMotPasse.getText();
        if(text2.equals(text1))
        {
            int option = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier votre mot de passe ", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (option == JOptionPane.YES_OPTION)
            {      this.setEnabled(false);
                
                try { 
                    chargeur = (Statement) bd.getJDBConnection().createStatement();
                    chargeur.executeUpdate("update Utilisateur set motDePas='"+text1+"' where numUtilisateur="+this.numUtilisateur+" and motDePas ='"+text+"' ");
                    chargeur.executeUpdate("UPDATE mysql.user SET Password = PASSWORD('"+text1+"') WHERE User = '"+this.user+"' AND Host = '"+this.Host+"'");
                    chargeur.executeUpdate("FLUSH PRIVILEGES");
                    chargeur.close();
                    JOptionPane.showMessageDialog(this, "Modification réussie");
                    
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Erreur SQL: "+ex.getMessage()+" \n Veillez les uniformiser !");
                }
                this.setEnabled(true); 
            }
        }
        else JOptionPane.showMessageDialog(this, "Les deux (2) nouveaux mots de passe ne sont conformes \n Veillez les uniformiser !");
    }//GEN-LAST:event_modifyPasswordMouseClicked

    private void actuelMotPasseTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_actuelMotPasseTextValueChanged
        String text = actuelMotPasse.getText();               
            if(text.equals(this.Password)){modifyPassword.setVisible(true);}
            else modifyPassword.setVisible(false);
        
    }//GEN-LAST:event_actuelMotPasseTextValueChanged

    private void confirmerNouveauMotDePasseTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_confirmerNouveauMotDePasseTextValueChanged
        String text1 = NouveauMotDePasse.getText(), text2= confirmerNouveauMotDePasse.getText();
        if(text2.equals(text1))
        {
            confirmerNouveauMotDePasse.setForeground(new java.awt.Color(0,0,255));
        }
        else confirmerNouveauMotDePasse.setForeground(new java.awt.Color(255, 0, 51));
    }//GEN-LAST:event_confirmerNouveauMotDePasseTextValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JChangerPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JChangerPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JChangerPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JChangerPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JChangerPassword dialog = null;
               
                    dialog = new JChangerPassword(new javax.swing.JFrame(), true, 26, "localhost", "AKS", "19900");
               
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField NouveauMotDePasse;
    private java.awt.TextField actuelMotPasse;
    private java.awt.TextField confirmerNouveauMotDePasse;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modifyPassword;
    // End of variables declaration//GEN-END:variables
}
