/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sgme.carder;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Senghor AKOMINON
 */
public final class JFicheImprimerBR extends javax.swing.JFrame 
{

    /**
     * Creates new form NewJFrame
     * @param refBR
     * @param refDR
     * @param prestataire
     * @param Adresse
     * @param CategorieMateriel
     * @param codMat
     * @param TSModel
     * @param date
     */
    public JFicheImprimerBR(String refBR, String refDR, String prestataire, String Adresse, String CategorieMateriel, String codMat, JTravailSignaleModel TSModel, String date) 
    {
          initComponents();
        tfRefBR.setText(refBR);
        tfRefDR.setText(refDR);
        tfNomPrestataire.setText(prestataire);
        tfAdressePrestataire.setText(Adresse);
        tfCategorieMateriel.setText(CategorieMateriel);
        tfCodMateriel.setText(codMat);
        tfDateEdition.setText(date);
        TSModel.addTravailSignale(new JTravailSignale("Totaux", ""+TSModel.getMainOuvreTotal()+"", TSModel.getCoutPieceTotal()) );
        //TSModel.addTravailSignale(new JTravailSignale("Total", TSModel.getMainOuvreTotal()+ TSModel.getCoutPieceTotal(),0) );
        try{
        tableauTS.setModel(TSModel);
        }catch(Exception e){JOptionPane.showMessageDialog(rootPane, e);}
        setPanelSize((int)this.getSize().getWidth(), (int)this.getSize().getHeight());
        
        
    }
    public JPanel getPanel()
    {
        return this.plContenaire;
    }
        public void setPanelSize(int w, int h)
    {
        this.plContenaire.setSize(w, h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plContenaire = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tfDateEdition = new javax.swing.JTextField();
        tfRefBR = new javax.swing.JTextField();
        tfRefDR = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tfNomPrestataire = new javax.swing.JTextField();
        tfAdressePrestataire = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tfCategorieMateriel = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tfCodMateriel = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableauTS = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        tfNomDAF = new javax.swing.JTextField();
        tfNomDG = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        plContenaire.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 204));
        jLabel25.setText("CARDER Borgou / Alibori");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("********");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 0, 0));
        jLabel27.setText("Service de Matériels et d'entretiens");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("Parakou, le ");

        tfDateEdition.setEditable(false);
        tfDateEdition.setBackground(new java.awt.Color(255, 255, 255));
        tfDateEdition.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfDateEdition.setBorder(null);
        tfDateEdition.setFocusable(false);

        tfRefBR.setEditable(false);
        tfRefBR.setBackground(new java.awt.Color(255, 255, 255));
        tfRefBR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfRefBR.setBorder(null);
        tfRefBR.setFocusable(false);
        tfRefBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRefBRActionPerformed(evt);
            }
        });

        tfRefDR.setEditable(false);
        tfRefDR.setBackground(new java.awt.Color(255, 255, 255));
        tfRefDR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfRefDR.setBorder(null);
        tfRefDR.setFocusable(false);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setText("BON DE REPARATION         N° ");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("Référence demande de Réparation    N°  ");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel31.setText("Nom du Prestataire : ");

        tfNomPrestataire.setEditable(false);
        tfNomPrestataire.setBackground(new java.awt.Color(255, 255, 255));
        tfNomPrestataire.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfNomPrestataire.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNomPrestataire.setBorder(null);
        tfNomPrestataire.setFocusable(false);

        tfAdressePrestataire.setEditable(false);
        tfAdressePrestataire.setBackground(new java.awt.Color(255, 255, 255));
        tfAdressePrestataire.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfAdressePrestataire.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAdressePrestataire.setBorder(null);
        tfAdressePrestataire.setFocusable(false);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setText("Adresse :");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel33.setText("Catégorie de Matériel :");

        tfCategorieMateriel.setEditable(false);
        tfCategorieMateriel.setBackground(new java.awt.Color(255, 255, 255));
        tfCategorieMateriel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfCategorieMateriel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCategorieMateriel.setBorder(null);
        tfCategorieMateriel.setFocusable(false);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel34.setText("Code Matériel :");

        tfCodMateriel.setEditable(false);
        tfCodMateriel.setBackground(new java.awt.Color(255, 255, 255));
        tfCodMateriel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfCodMateriel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCodMateriel.setBorder(null);
        tfCodMateriel.setFocusable(false);

        tableauTS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tableauTS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tableauTS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N°  Ordre", "Travaux Signalés", "Main d'Ouvre", "Coût Pièce"
            }
        ));
        tableauTS.setFocusable(false);
        tableauTS.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(tableauTS);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Le Directeur Général");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Visa D. A. F.");

        tfNomDAF.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfNomDAF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNomDAF.setText("T. Jean-Marie BIAOU");
        tfNomDAF.setBorder(null);
        tfNomDAF.setFocusable(false);

        tfNomDG.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfNomDG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNomDG.setText("Senghor AKOMINON");
        tfNomDG.setBorder(null);
        tfNomDG.setFocusable(false);

        javax.swing.GroupLayout plContenaireLayout = new javax.swing.GroupLayout(plContenaire);
        plContenaire.setLayout(plContenaireLayout);
        plContenaireLayout.setHorizontalGroup(
            plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plContenaireLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plContenaireLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(plContenaireLayout.createSequentialGroup()
                                .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(plContenaireLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNomPrestataire, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfAdressePrestataire, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, plContenaireLayout.createSequentialGroup()
                                        .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfCodMateriel)
                                            .addComponent(tfCategorieMateriel))))
                                .addGap(555, 555, 555))
                            .addGroup(plContenaireLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDateEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(402, 402, 402))))
                    .addGroup(plContenaireLayout.createSequentialGroup()
                        .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNomDAF, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(plContenaireLayout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(plContenaireLayout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfRefDR, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(plContenaireLayout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfRefBR, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(plContenaireLayout.createSequentialGroup()
                        .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfNomDG, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(plContenaireLayout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(220, 220, 220)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27)
                                    .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(plContenaireLayout.createSequentialGroup()
                                            .addGap(33, 33, 33)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        plContenaireLayout.setVerticalGroup(
            plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plContenaireLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(tfDateEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRefBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRefDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plContenaireLayout.createSequentialGroup()
                        .addComponent(tfNomPrestataire, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfAdressePrestataire, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCategorieMateriel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plContenaireLayout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48))
                    .addGroup(plContenaireLayout.createSequentialGroup()
                        .addComponent(tfCodMateriel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel35))
                .addGap(59, 59, 59)
                .addGroup(plContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNomDAF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plContenaire, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plContenaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfRefBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRefBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRefBRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFicheImprimerBR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFicheImprimerBR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFicheImprimerBR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFicheImprimerBR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFicheImprimerBR(null, null, null, null, null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel plContenaire;
    private javax.swing.JTable tableauTS;
    private javax.swing.JTextField tfAdressePrestataire;
    private javax.swing.JTextField tfCategorieMateriel;
    private javax.swing.JTextField tfCodMateriel;
    private javax.swing.JTextField tfDateEdition;
    private javax.swing.JTextField tfNomDAF;
    private javax.swing.JTextField tfNomDG;
    private javax.swing.JTextField tfNomPrestataire;
    private javax.swing.JTextField tfRefBR;
    private javax.swing.JTextField tfRefDR;
    // End of variables declaration//GEN-END:variables
}
